-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "reportTypes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""reportTypes_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1),
	"name" varchar NOT NULL,
	"description" varchar
);
--> statement-breakpoint
CREATE TABLE "secrets" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "secrets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar NOT NULL,
	"createdAt" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text),
	"deletedOn" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text),
	"count" bigint,
	"lastRetrieveAt" timestamp,
	CONSTRAINT "secrets_name_key" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "configures" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "configures_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"key" varchar NOT NULL,
	"value" varchar NOT NULL,
	"description" varchar
);
--> statement-breakpoint
CREATE TABLE "reports" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reports_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"postId" bigint NOT NULL,
	"reportTypeId" bigint,
	"reportMessage" varchar,
	"reportIpaddress" varchar,
	"reportDate" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text),
	"isProcessed" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "posts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "posts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"secretId" bigint NOT NULL,
	"title" varchar,
	"text" varchar,
	"isDeleted" boolean DEFAULT false NOT NULL,
	"ipaddress" varchar,
	"createdAt" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text),
	"deletedOn" timestamp,
	"attachments" varchar[],
	"uuid" uuid DEFAULT gen_random_uuid(),
	"updatedOn" timestamp
);
--> statement-breakpoint
ALTER TABLE "reports" ADD CONSTRAINT "reports_postId_fkey" FOREIGN KEY ("postId") REFERENCES "public"."posts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reports" ADD CONSTRAINT "reports_reportTypeId_fkey" FOREIGN KEY ("reportTypeId") REFERENCES "public"."reportTypes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "posts" ADD CONSTRAINT "posts_secretId_fkey" FOREIGN KEY ("secretId") REFERENCES "public"."secrets"("id") ON DELETE cascade ON UPDATE no action;
*/